language: r
cache: packages
latex: false

matrix:
  include:
  - os: linux
    dist: xenial
    r: release
  - os: linux
    dist: xenial
    r: devel
  - os: osx
    osx_image: xcode11.6
    r: release
  - os: osx
    osx_image: xcode11.6
    r: devel

warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:opencpu/poppler'
    packages:
    - libpoppler-cpp-dev
    - libpoppler-cpp0v5

before_install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_deps(dependencies = TRUE)'

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran
