name: R Package Build carbonVisR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        r-version: ['4.3.2']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install Dependencies
        working-directory: 534_R_package/carbonVisR
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            R -e 'install.packages(c("remotes", "rcmdcheck", "usethis", "tidyr", "dplyr", "lubridate", "ggplot2", "ggthemes", "RColorBrewer", "scales", "httr"), dependencies = TRUE)'
          elif [ "${{ runner.os }}" = "macOS" ]; then
            R -e 'install.packages(c("remotes", "rcmdcheck", "usethis", "tidyr", "dplyr", "lubridate", "ggplot2", "ggthemes", "RColorBrewer", "scales", "httr"), dependencies = TRUE)'
          elif [ "${{ runner.os }}" = "Windows" ]; then
            R -e 'install.packages(c("remotes", "rcmdcheck", "usethis", "tidyr", "dplyr", "lubridate", "ggplot2", "ggthemes", "RColorBrewer", "scales", "httr"), dependencies = TRUE)'
          fi
        shell: bash {0}

      - name: Check Package
        working-directory: 534_R_package/carbonVisR
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
